# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: yarn
      - name: Build Github Pages
        run: yarn buildgh
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

      # - name: Build
      #   run: yarn build
      # - name: 📂 Sync files to https://get.ledfx.app
      #   continue-on-error: true
      #   uses: SamKirkland/FTP-Deploy-Action@2.0.0
      #   env:
      #     FTP_SERVER: ${{ secrets.FTP_SERVER }}
      #     FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
      #     FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      #     PORT: 22
      #     METHOD: sftp
      #     LOCAL_DIR: ./dist/
      #     REMOTE_DIR: ./download.ledfx.app/

  deploy-second-repo:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout second repo
        uses: actions/checkout@v4
        with:
          repository: LedFx/LedFx-Download
          token: ${{ secrets.SECOND_REPO_TOKEN }}
      - name: Deploy to second GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          path: './dist'
          target_branch: 'gh-pages'
          commit_message: 'Deployed to gh-pages'
